name: dry
description: Do not apply water
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

#dependencies:

dev_dependencies:
  test: ^1.21.3
  flutter_lints: ^3.0.1
dependencies:
  characters: ^1.3.0
